"""Validation harness — measures precision, recall, and F1 against ground truth.

Reports the **false-positive rate on "same_product_different_color" pairs**
as a dedicated metric — this is the single most important number in the
entire project.

Usage::

    python validation/evaluate.py \\
        --report-dir output/ \\
        --ground-truth validation/ground_truth.csv

The report directory must contain the CSV output from the pipeline
(``report.csv`` or any ``.csv`` file generated by ``report.py``).
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import defaultdict
from pathlib import Path


def load_ground_truth(path: Path) -> list[dict]:
    """Load the labeled ground-truth pairs.

    Args:
        path: Path to ``ground_truth.csv``.

    Returns:
        List of dicts with keys: ``image_a``, ``image_b``,
        ``is_duplicate`` (bool), ``category`` (str).
    """
    rows: list[dict] = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(
                {
                    "image_a": row["image_a"].strip(),
                    "image_b": row["image_b"].strip(),
                    "is_duplicate": row["is_duplicate"].strip().lower() == "true",
                    "category": row["category"].strip(),
                }
            )
    return rows


def load_pipeline_groups(report_dir: Path) -> dict[str, int]:
    """Load pipeline output and build a filename → group_id mapping.

    Args:
        report_dir: Directory containing the pipeline's CSV output.

    Returns:
        Mapping of ``{file_name: group_id}``.
    """
    csv_files = list(report_dir.glob("*.csv"))
    if not csv_files:
        print(f"No CSV files found in {report_dir}", file=sys.stderr)
        return {}

    # Use the first CSV found (there should be exactly one)
    csv_path = csv_files[0]
    mapping: dict[str, int] = {}

    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            fname = row.get("file_name", "").strip()
            gid = row.get("group_id", "").strip()
            if fname and gid:
                mapping[fname] = int(gid)

    return mapping


def evaluate(
    ground_truth: list[dict],
    group_map: dict[str, int],
) -> dict:
    """Compute precision, recall, F1, and per-category metrics.

    Args:
        ground_truth: Labeled pairs from ``ground_truth.csv``.
        group_map: Filename → group_id mapping from pipeline output.

    Returns:
        Dict with overall and per-category metrics.
    """
    tp = 0  # true positive: GT=duplicate, pipeline=same group
    fp = 0  # false positive: GT=not duplicate, pipeline=same group
    fn = 0  # false negative: GT=duplicate, pipeline=different group
    tn = 0  # true negative: GT=not duplicate, pipeline=different group

    category_fp: dict[str, int] = defaultdict(int)
    category_fn: dict[str, int] = defaultdict(int)
    category_tp: dict[str, int] = defaultdict(int)
    category_tn: dict[str, int] = defaultdict(int)
    category_total: dict[str, int] = defaultdict(int)

    for pair in ground_truth:
        a = pair["image_a"]
        b = pair["image_b"]
        is_dup = pair["is_duplicate"]
        cat = pair["category"]

        ga = group_map.get(a)
        gb = group_map.get(b)

        # Pipeline says "duplicate" if both are in the same group
        pipeline_says_dup = ga is not None and gb is not None and ga == gb

        category_total[cat] += 1

        if is_dup and pipeline_says_dup:
            tp += 1
            category_tp[cat] += 1
        elif is_dup and not pipeline_says_dup:
            fn += 1
            category_fn[cat] += 1
        elif not is_dup and pipeline_says_dup:
            fp += 1
            category_fp[cat] += 1
        else:
            tn += 1
            category_tn[cat] += 1

    precision = tp / (tp + fp) if (tp + fp) > 0 else 1.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 1.0
    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else 0.0
    )

    # The critical metric: FP rate on same_product_different_color
    diff_color_total = category_total.get("same_product_different_color", 0)
    diff_color_fp = category_fp.get("same_product_different_color", 0)
    diff_color_fp_rate = (
        diff_color_fp / diff_color_total if diff_color_total > 0 else 0.0
    )

    return {
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "diff_color_fp_rate": diff_color_fp_rate,
        "diff_color_fp_count": diff_color_fp,
        "diff_color_total": diff_color_total,
        "category_fp": dict(category_fp),
        "category_fn": dict(category_fn),
        "category_tp": dict(category_tp),
        "category_tn": dict(category_tn),
        "category_total": dict(category_total),
    }


def print_report(metrics: dict) -> None:
    """Print a formatted validation report to stdout.

    Args:
        metrics: Dict returned by :func:`evaluate`.
    """
    print("=" * 60)
    print("VALIDATION REPORT")
    print("=" * 60)
    print()
    print("Overall Metrics:")
    print(f"  True Positives:   {metrics['tp']}")
    print(f"  False Positives:  {metrics['fp']}")
    print(f"  False Negatives:  {metrics['fn']}")
    print(f"  True Negatives:   {metrics['tn']}")
    print()
    print(f"  Precision:        {metrics['precision']:.4f}")
    print(f"  Recall:           {metrics['recall']:.4f}")
    print(f"  F1 Score:         {metrics['f1']:.4f}")
    print()
    print("=" * 60)
    print("CRITICAL METRIC — Same Shape, Different Color")
    print("=" * 60)
    print(f"  Total pairs:      {metrics['diff_color_total']}")
    print(f"  False positives:  {metrics['diff_color_fp_count']}")
    print(f"  FP Rate:          {metrics['diff_color_fp_rate']:.4f}")
    if metrics["diff_color_fp_rate"] > 0:
        print()
        print("  ⚠️  WARNING: Non-zero false-positive rate on different-color pairs!")
        print("  These pairs were incorrectly flagged as duplicates.")
    else:
        print()
        print("  ✅ Zero false positives on different-color pairs.")
    print()

    # Per-category breakdown
    print("=" * 60)
    print("Per-Category Breakdown:")
    print("=" * 60)
    for cat in sorted(metrics["category_total"]):
        total = metrics["category_total"][cat]
        tp = metrics["category_tp"].get(cat, 0)
        fp = metrics["category_fp"].get(cat, 0)
        fn = metrics["category_fn"].get(cat, 0)
        tn = metrics["category_tn"].get(cat, 0)
        print(f"  {cat}:")
        print(f"    Total={total}  TP={tp}  FP={fp}  FN={fn}  TN={tn}")


def main() -> int:
    """CLI entry point for the validation harness."""
    parser = argparse.ArgumentParser(
        description="Evaluate pipeline output against ground truth."
    )
    parser.add_argument(
        "--report-dir",
        type=Path,
        required=True,
        help="Directory containing the pipeline's CSV output.",
    )
    parser.add_argument(
        "--ground-truth",
        type=Path,
        required=True,
        help="Path to the ground_truth.csv file.",
    )

    args = parser.parse_args()

    if not args.ground_truth.is_file():
        print(f"Ground truth not found: {args.ground_truth}", file=sys.stderr)
        return 1
    if not args.report_dir.is_dir():
        print(f"Report directory not found: {args.report_dir}", file=sys.stderr)
        return 1

    gt = load_ground_truth(args.ground_truth)
    group_map = load_pipeline_groups(args.report_dir)
    metrics = evaluate(gt, group_map)
    print_report(metrics)

    # Exit code: 0 if no different-color FPs, 1 otherwise
    return 0 if metrics["diff_color_fp_rate"] == 0.0 else 1


if __name__ == "__main__":
    sys.exit(main())
